### ISSUE TITLE
Can you use this with vanilla code-push?

### ISSUE THREAD

**Issue by faceyspacey** [electrode-io/electrode-ota-desktop#2]
i.e. without having to setup my own electrode-ota server? 

...Nice work by the way! Was imagining something similar myself.

**Comment by jspears** [comment]
Yes, you should be able to by entering the microsoft codepush server as the "host"

https://codepush-management.azurewebsites.net

I should put that in the docs somewhere.

**Comment by faceyspacey** [comment]
this is going to be very popular then. might even be the bridge that brings people over to using more of the electrode offering. For example, I personally am ready to use this since it works with the standard code push server, but am not ready to host my own code push distribution server.
